### ISSUE TITLE
Crash when opening api.cc

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#55]
libclang: crash detected during reparsing

More info needed.

**Comment by zalox** [comment]
I think this could be invalid json-file. Since libclang opens compile_commands.json and it doesn't contain api.cc it crashes. At least my first thought.

**Comment by eidheim** [comment]
gdb backtrace output:
```gdb
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x1c2b of process 91879]
0x00000001005c3a50 in bool clang::Decl::hasAttr<clang::NoReturnAttr>() const () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
(gdb) backtrace
#0  0x00000001005c3a50 in bool clang::Decl::hasAttr<clang::NoReturnAttr>() const () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#1  0x0000000100253b69 in clang::FunctionDecl::isNoReturn() const () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#2  0x000000010097d588 in (anonymous namespace)::CFGBuilder::addAutomaticObjDtors((anonymous namespace)::LocalScope::const_iterator, (anonymous namespace)::LocalScope::const_iterator, clang::Stmt*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#3  0x000000010097d05d in (anonymous namespace)::CFGBuilder::VisitCompoundStmt(clang::CompoundStmt*) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#4  0x000000010097a7bb in (anonymous namespace)::CFGBuilder::Visit(clang::Stmt*, (anonymous namespace)::AddStmtChoice) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#5  0x0000000100977af5 in clang::CFG::buildCFG(clang::Decl const*, clang::Stmt*, clang::ASTContext*, clang::CFG::BuildOptions const&) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#6  0x00000001009748f0 in clang::AnalysisDeclContext::getCFG() () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#7  0x000000010043413d in clang::sema::AnalysisBasedWarnings::IssueWarnings(clang::sema::AnalysisBasedWarnings::Policy, clang::sema::FunctionScopeInfo*, clang::Decl const*, clang::BlockExpr const*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#8  0x0000000100467499 in clang::Sema::PopFunctionScopeInfo(clang::sema::AnalysisBasedWarnings::Policy const*, clang::Decl const*, clang::BlockExpr const*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#9  0x00000001004eacae in clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#10 0x0000000100888efd in clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#11 0x0000000100896ffe in clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#12 0x0000000100844b33 in clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#13 0x00000001008966fe in clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#14 0x00000001008962df in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#15 0x0000000100895b52 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#16 0x0000000100895255 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#17 0x00000001008384b5 in clang::ParseAST(clang::Sema&, bool, bool) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#18 0x00000001003b7ecb in clang::FrontendAction::Execute() () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#19 0x000000010038563c in clang::ASTUnit::Parse(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >) ()
   from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#20 0x000000010038956d in clang::ASTUnit::Reparse(llvm::ArrayRef<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, llvm::MemoryBuffer*> >) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#21 0x00000001001a466a in clang_reparseTranslationUnit_Impl(void*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#22 0x0000000100798058 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#23 0x00000001007981b2 in RunSafelyOnThread_Dispatch(void*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#24 0x00000001007c42e3 in ExecuteOnThread_Dispatch(void*) () from /usr/local/opt/llvm/lib/libclang.3.6.dylib
#25 0x00007fff87ed0899 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#26 0x00007fff87ed072a in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#27 0x00007fff87ed4fc9 in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#28 0x0000000000000000 in ?? ()
```
